### ISSUE TITLE
Not detect barcode 21 Character 

### ISSUE THREAD

**Issue by mesismart** [Scandit/scandit-react-native-datacapture-barcode#9]
Hi , at first I Install Scandit Demo Application from site and test my barcode and it's worked . after that I run BarcodeCaptureSimpleSample and Run in My device , after test it's not detect my barcode !!!  I addition to i tested it on lower character (16 char) barcode and work well . but I Don't know why this SDK no action in my barcode but Scandit Demo work well !!! 
anyone have solution for that ?

this is my barcode 
![barcode21](https://user-images.githubusercontent.com/69520192/204079019-369d7bf8-760b-4a09-97aa-eb2d71869b74.png)

**Comment by ScanditSupport** [comment]
Hi,

The error you are experiencing is caused by the symbol count of the barcode. Here you will find our documentation regarding how to increase the symbol count: https://docs.scandit.com/data-capture-sdk/cordova/barcode-capture/api/barcode.html?highlight=symbol%20count#property-scandit.datacapture.barcode.Barcode.SymbolCount

Please note that this symbology is code39, here you can find the default data for each symbology: https://docs.scandit.com/data-capture-sdk/cordova/barcode-capture/symbology-properties.html?highlight=symbol%20count

In case you have more detailed questions, please feel free to reach out to us directly: https://support.scandit.com/hc/en-us/requests/new.

Best regards

Scandit Support Team
